image: checkmarx/ast-cli
 
pipelines:
  default:
    - step:
        script:
          - /app/bin/cx scan create -s $BITBUCKET_CLONE_DIR --project-name $BITBUCKET_WORKSPACE/$BITBUCKET_REPO_SLUG --branch $BITBUCKET_BRANCH --base-uri $BASE_URI --tenant $TENANT --client-id $CLIENT_ID --client-secret $CLIENT_SECRET 