trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Checkmarx_Scans
    jobs:
    - job: scan
      steps:
      - script: |
          mkdir cx-cli; cd cx-cli
          curl -Lo ast-cli.tar.gz https://github.com/Checkmarx/ast-cli/releases/download/2.3.32/ast-cli_2.3.32_linux_x64.tar.gz
          tar -xzvf ast-cli.tar.gz
          ./cx scan create -s $(Build.Repository.LocalPath) --project-name $(system.teamProject) --branch $(Build.SourceBranchName) --base-uri $(CX_BASE_URI) --tenant $(CX_TENANT) --client-id $(CX_CLIENT_ID) --client-secret $(CX_CLIENT_SECRET) --scan-types sast,sca,scs,container-security,iac-security
        displayName: 'Checkmarx'